import { Router, type IRouter } from "express";
import healthRouter from "./health";
import publicRouter from "./public";
import ogRouter from "./og";
import usersRouter from "./users";
import eventsRouter from "./events";
import forumRouter from "./forum";
import resourcesRouter from "./resources";
import marketplaceRouter from "./marketplace";
import notificationsRouter from "./notifications";
import adminRouter from "./admin";
import reportsRouter from "./reports";
import communityRouter from "./community";
import landingRouter from "./landing";
import storageRouter from "./storage";
import webhooksRouter from "./webhooks";
import seoRouter from "./seo";
import referralsRouter from "./referrals";
import coursesRouter from "./courses";

const router: IRouter = Router();

router.use(seoRouter);
router.use(healthRouter);
router.use(publicRouter);
router.use(ogRouter);
router.use(communityRouter);
router.use(webhooksRouter);
router.use(usersRouter);
router.use(eventsRouter);
router.use(forumRouter);
router.use(resourcesRouter);
router.use(marketplaceRouter);
router.use(notificationsRouter);
router.use(adminRouter);
router.use(reportsRouter);
router.use(landingRouter);
router.use(storageRouter);
router.use(referralsRouter);
router.use(coursesRouter);

export default router;
